# Image בסיסי
FROM node:20

# מתקין ffmpeg ו yt-dlp
RUN apt update && \
    apt install -y ffmpeg python3-pip && \
    pip install yt-dlp

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 3000

CMD ["node", "server.js"]
