FROM node:18

# התקן yt-dlp
RUN apt-get update \
 && apt-get install -y ffmpeg wget \
 && wget https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp \
 && chmod a+rx yt-dlp \
 && mv yt-dlp /usr/local/bin/yt-dlp

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "start"]
